// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarManagementApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241216085427_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Features = "Hybrid, Sedan",
                            Model = "Camry",
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Features = "Compact, Efficient",
                            Model = "Corolla",
                            Year = 2021
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            Features = "Compact SUV, AWD",
                            Model = "RAV4",
                            Year = 2023
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            Features = "Hybrid, Eco-Friendly",
                            Model = "Prius",
                            Year = 2020
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            Features = "Sport, V8 Engine",
                            Model = "Mustang",
                            Year = 2021
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            Features = "Pickup Truck, Towing Capacity",
                            Model = "F-150",
                            Year = 2022
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            Features = "SUV, Family Car",
                            Model = "Explorer",
                            Year = 2023
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            Features = "Compact, Efficient",
                            Model = "Focus",
                            Year = 2020
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 3,
                            Features = "Luxury SUV",
                            Model = "X5",
                            Year = 2020
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            Features = "Luxury Sedan, Sporty",
                            Model = "3 Series",
                            Year = 2021
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            Features = "Executive Sedan, Comfort",
                            Model = "5 Series",
                            Year = 2022
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            Features = "High-Performance Sedan",
                            Model = "M3",
                            Year = 2023
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 4,
                            Features = "Compact, Reliable",
                            Model = "Civic",
                            Year = 2021
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 4,
                            Features = "Midsize Sedan, Fuel Efficient",
                            Model = "Accord",
                            Year = 2022
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 4,
                            Features = "SUV, AWD",
                            Model = "CR-V",
                            Year = 2023
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 4,
                            Features = "SUV, Spacious",
                            Model = "Pilot",
                            Year = 2020
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 5,
                            Features = "Pickup Truck, Durable",
                            Model = "Silverado",
                            Year = 2021
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 5,
                            Features = "Midsize Sedan, Comfortable",
                            Model = "Malibu",
                            Year = 2022
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 5,
                            Features = "Full-Size SUV, Powerful",
                            Model = "Tahoe",
                            Year = 2023
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 5,
                            Features = "Sport Coupe, Iconic",
                            Model = "Camaro",
                            Year = 2020
                        });
                });

            modelBuilder.Entity("CarBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CarBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Japan",
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Germany",
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Japan",
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 5,
                            Country = "USA",
                            Name = "Chevrolet"
                        });
                });

            modelBuilder.Entity("Car", b =>
                {
                    b.HasOne("CarBrand", "CarBrand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarBrand");
                });

            modelBuilder.Entity("CarBrand", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
